
# hero,engineer,soldier,soldier,soldier,sentry,outpost,base
blood_array = [100,100,100,100,100,400,0,1500,
100,100,100,100,100,400,1500,500]
game_time = 10
robot_id = 107
allow_bullet = 2
vitual_mode = 0
wait_seconds = 0
use_time = 1

cmd_keyboard = 'Q'

# robot_position_array = [[2.0,5.0],[13.0,5.0],[4.0,5.0],[4.0,2.5],[3.0,2.5],[12.5,0.5]]
# robot_id_array = [1,2,3,10,11,12]

robot_position_array = []
robot_id_array = []
self_position = [5.0,5.0]

# trans_matrix = [0.0,-1.0,5.08]
# [1.0,0.0,-6.16] 

target_position_x = 8.16
target_position_y = 6.08
